sudo: required
language: python
python: 3.7
dist: xenial
sudo: true
services:
  - docker
stages:
  - test
  - generate_visual_map
  - visual_metadata_dump
  - docker_hub_push
  - deploy_dev
addons:
  ssh_known_hosts: $BOX

jobs:
  include:
    - stage: test
      name: Test
      script: "./cmd-dict.sh unittest"
    - stage: generate_visual_map
      name: generate visual map
      script: "./cmd-dict.sh generate_visual_map"
    - stage: visual_metadata_dump
      name: visual metadata dump
      script: "./cmd-dict.sh visual_metadata_dump"  
    - stage: docker_hub_push
      name: Docker hub push
      script: "./cmd-dict.sh dockerHubPush"
    - stage: deploy_dev
      name: Deploy dev
      script: "./cmd-dict.sh deploy dev"
before_install:
  - openssl aes-256-cbc -K $encrypted_b1d5dc4a027b_key -iv $encrypted_b1d5dc4a027b_iv -in deploy_key.enc -out deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_key
  - ssh-add deploy_key